-- Leads import and distribution schema (admin -> user/campaign)

create table if not exists public.lead_import_batches (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  uploaded_by_admin_id uuid not null references auth.users(id),
  assigned_user_id uuid not null references auth.users(id),
  campaign_id bigint not null references public.campaigns(id),
  source_filename text not null,
  total_rows integer not null default 0,
  valid_rows integer not null default 0,
  inserted_rows integer not null default 0,
  duplicate_rows integer not null default 0,
  invalid_rows integer not null default 0,
  meta jsonb not null default '{}'::jsonb
);

create index if not exists idx_lead_batches_assigned_user_created_at
  on public.lead_import_batches (assigned_user_id, created_at desc);

create index if not exists idx_lead_batches_campaign_created_at
  on public.lead_import_batches (campaign_id, created_at desc);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  batch_id bigint not null references public.lead_import_batches(id) on delete cascade,
  assigned_user_id uuid not null references auth.users(id),
  campaign_id bigint not null references public.campaigns(id),
  email text not null,
  email_normalized text not null,
  payload_json jsonb not null default '{}'::jsonb,
  constraint leads_email_normalized_chk
    check (email_normalized = lower(trim(email_normalized)))
);

create unique index if not exists ux_leads_email_normalized
  on public.leads (email_normalized);

create index if not exists idx_leads_batch_id
  on public.leads (batch_id);

create index if not exists idx_leads_assigned_user_created_at
  on public.leads (assigned_user_id, created_at desc);

create table if not exists public.lead_import_rejections (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  batch_id bigint not null references public.lead_import_batches(id) on delete cascade,
  row_number integer not null,
  email_raw text,
  reason text not null check (reason in ('duplicate', 'invalid_email', 'missing_email')),
  details jsonb not null default '{}'::jsonb
);

create index if not exists idx_lead_rejections_batch_id
  on public.lead_import_rejections (batch_id);

alter table public.lead_import_batches enable row level security;
alter table public.leads enable row level security;
alter table public.lead_import_rejections enable row level security;

create policy lead_batches_admin_all
  on public.lead_import_batches
  for all
  to authenticated
  using (
    (select p.role from public.profiles p where p.id = auth.uid()) = 'admin'
  )
  with check (
    (select p.role from public.profiles p where p.id = auth.uid()) = 'admin'
  );

create policy lead_batches_user_select_own
  on public.lead_import_batches
  for select
  to authenticated
  using (assigned_user_id = auth.uid());

create policy leads_admin_all
  on public.leads
  for all
  to authenticated
  using (
    (select p.role from public.profiles p where p.id = auth.uid()) = 'admin'
  )
  with check (
    (select p.role from public.profiles p where p.id = auth.uid()) = 'admin'
  );

create policy leads_user_select_own
  on public.leads
  for select
  to authenticated
  using (assigned_user_id = auth.uid());

create policy lead_rejections_admin_all
  on public.lead_import_rejections
  for all
  to authenticated
  using (
    (select p.role from public.profiles p where p.id = auth.uid()) = 'admin'
  )
  with check (
    (select p.role from public.profiles p where p.id = auth.uid()) = 'admin'
  );

create policy lead_rejections_user_select_own
  on public.lead_import_rejections
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.lead_import_batches b
      where b.id = lead_import_rejections.batch_id
        and b.assigned_user_id = auth.uid()
    )
  );

grant select, insert, update, delete on public.lead_import_batches to authenticated;
grant select, insert, update, delete on public.leads to authenticated;
grant select, insert, update, delete on public.lead_import_rejections to authenticated;

grant usage, select on sequence public.lead_import_batches_id_seq to authenticated;
grant usage, select on sequence public.leads_id_seq to authenticated;
grant usage, select on sequence public.lead_import_rejections_id_seq to authenticated;

create or replace function public.admin_leads_import_preview(
  p_assigned_user_id uuid,
  p_campaign_id bigint,
  p_emails text[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  duplicate_count integer := 0;
  candidate_count integer := 0;
  duplicate_samples jsonb := '[]'::jsonb;
begin
  if not exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ) then
    raise exception 'Access denied: admin only';
  end if;

  if not exists (
    select 1
    from public.campaigns c
    where c.id = p_campaign_id
      and c.user_id = p_assigned_user_id
  ) then
    raise exception 'Campaign does not belong to selected user';
  end if;

  with normalized as (
    select lower(trim(email_input)) as email
    from unnest(coalesce(p_emails, '{}'::text[])) email_input
  ),
  candidates as (
    select distinct n.email
    from normalized n
    where n.email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$'
  ),
  duplicates as (
    select c.email
    from candidates c
    join public.leads l on l.email_normalized = c.email
  )
  select
    (select count(*) from candidates),
    (select count(*) from duplicates),
    coalesce((
      select jsonb_agg(d.email)
      from (
        select email from duplicates order by email limit 20
      ) d
    ), '[]'::jsonb)
  into candidate_count, duplicate_count, duplicate_samples;

  return jsonb_build_object(
    'candidate_count', candidate_count,
    'duplicate_count', duplicate_count,
    'new_count', greatest(candidate_count - duplicate_count, 0),
    'duplicate_samples', duplicate_samples
  );
end;
$$;

grant execute on function public.admin_leads_import_preview(uuid, bigint, text[]) to authenticated;

create or replace function public.admin_leads_import_confirm(
  p_assigned_user_id uuid,
  p_campaign_id bigint,
  p_source_filename text,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_batch_id bigint;
  v_total_rows integer := 0;
  v_valid_rows integer := 0;
  v_inserted_rows integer := 0;
  v_duplicate_rows integer := 0;
  v_invalid_rows integer := 0;
  v_duplicate_samples jsonb := '[]'::jsonb;
begin
  if not exists (
    select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
  ) then
    raise exception 'Access denied: admin only';
  end if;

  if not exists (
    select 1
    from public.campaigns c
    where c.id = p_campaign_id
      and c.user_id = p_assigned_user_id
  ) then
    raise exception 'Campaign does not belong to selected user';
  end if;

  if p_rows is null or jsonb_typeof(p_rows) <> 'array' then
    raise exception 'Invalid rows payload';
  end if;

  create temporary table _lead_import_stage (
    row_number integer not null,
    row_json jsonb not null,
    email_raw text,
    email_normalized text,
    is_valid boolean not null default false,
    is_duplicate_in_file boolean not null default false,
    is_duplicate_existing boolean not null default false
  ) on commit drop;

  insert into _lead_import_stage (row_number, row_json, email_raw, email_normalized, is_valid)
  select
    entry.ordinality::integer,
    entry.row_json,
    entry.row_json->>'email' as email_raw,
    lower(trim(coalesce(entry.row_json->>'email', ''))) as email_normalized,
    (
      lower(trim(coalesce(entry.row_json->>'email', ''))) ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$'
    ) as is_valid
  from jsonb_array_elements(p_rows) with ordinality as entry(row_json, ordinality);

  update _lead_import_stage s
  set is_duplicate_in_file = true
  where s.is_valid
    and exists (
      select 1
      from _lead_import_stage first_row
      where first_row.email_normalized = s.email_normalized
        and first_row.is_valid
        and first_row.row_number < s.row_number
    );

  update _lead_import_stage s
  set is_duplicate_existing = true
  where s.is_valid
    and not s.is_duplicate_in_file
    and exists (
      select 1
      from public.leads l
      where l.email_normalized = s.email_normalized
    );

  select count(*) into v_total_rows from _lead_import_stage;
  select count(*) into v_valid_rows from _lead_import_stage where is_valid;
  select count(*) into v_invalid_rows from _lead_import_stage where not is_valid;
  select count(*) into v_duplicate_rows
  from _lead_import_stage
  where is_duplicate_in_file or is_duplicate_existing;

  insert into public.lead_import_batches (
    uploaded_by_admin_id,
    assigned_user_id,
    campaign_id,
    source_filename,
    total_rows,
    valid_rows,
    inserted_rows,
    duplicate_rows,
    invalid_rows
  )
  values (
    auth.uid(),
    p_assigned_user_id,
    p_campaign_id,
    p_source_filename,
    v_total_rows,
    v_valid_rows,
    0,
    v_duplicate_rows,
    v_invalid_rows
  )
  returning id into v_batch_id;

  insert into public.leads (
    batch_id,
    assigned_user_id,
    campaign_id,
    email,
    email_normalized,
    payload_json
  )
  select
    v_batch_id,
    p_assigned_user_id,
    p_campaign_id,
    s.email_raw,
    s.email_normalized,
    coalesce(s.row_json - 'email', '{}'::jsonb)
  from _lead_import_stage s
  where s.is_valid
    and not s.is_duplicate_in_file
    and not s.is_duplicate_existing;

  get diagnostics v_inserted_rows = row_count;

  insert into public.lead_import_rejections (
    batch_id,
    row_number,
    email_raw,
    reason,
    details
  )
  select
    v_batch_id,
    s.row_number,
    s.email_raw,
    case
      when s.is_duplicate_in_file or s.is_duplicate_existing then 'duplicate'
      when s.email_normalized is null or s.email_normalized = '' then 'missing_email'
      else 'invalid_email'
    end,
    jsonb_build_object(
      'duplicate_in_file', s.is_duplicate_in_file,
      'duplicate_existing', s.is_duplicate_existing
    )
  from _lead_import_stage s
  where not (s.is_valid and not s.is_duplicate_in_file and not s.is_duplicate_existing);

  update public.lead_import_batches
  set inserted_rows = v_inserted_rows
  where id = v_batch_id;

  select coalesce(
    jsonb_agg(sample.email_normalized),
    '[]'::jsonb
  )
  into v_duplicate_samples
  from (
    select distinct s.email_normalized
    from _lead_import_stage s
    where s.is_duplicate_in_file or s.is_duplicate_existing
    order by s.email_normalized
    limit 20
  ) sample;

  return jsonb_build_object(
    'batch_id', v_batch_id,
    'total_rows', v_total_rows,
    'valid_rows', v_valid_rows,
    'inserted_rows', v_inserted_rows,
    'duplicate_rows', v_duplicate_rows,
    'invalid_rows', v_invalid_rows,
    'duplicate_samples', v_duplicate_samples
  );
end;
$$;

grant execute on function public.admin_leads_import_confirm(uuid, bigint, text, jsonb) to authenticated;
